services:
    mongodb:
        image: mongo:6.0
        restart: always
        command: [--auth, --replSet, repl0, --bind_ip_all, "--keyFile", "/data/key.key"]
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMIN_USR}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMIN_PWD}
            MONGO_INITDB_DATABASE: ${HOMUNCULUS_DB}
        ports:
            - 27017:27017
        networks:
            - mongo-network
        volumes:
            - ./seed/data/key.key:/data/key.key
        healthcheck:
            test: mongosh --username ${MONGODB_ADMIN_USR} --password ${MONGODB_ADMIN_PWD} --authenticationDatabase admin
            interval: 15s
            timeout: 5s
            retries: 5

    mongodb-init:
        build: ./auxiliary
        depends_on:
            mongodb:
                condition: service_healthy
        networks:
            - mongo-network
        environment:
            MONGODB_ADMIN_USR: ${MONGODB_ADMIN_USR}
            MONGODB_ADMIN_PWD: ${MONGODB_ADMIN_PWD}
            MONGODB_HOST: mongodb
            HOMUNCULUS_DB: ${HOMUNCULUS_DB}

    hermes:
        image: lotuxpunk/hermes:latest
        restart: always
        networks:
            - mongo-network
        volumes:
            - ./hermes/config/forms:/hermes/config/forms
            - ./hermes/config/mails:/hermes/config/mails
            - ./hermes/config/templates:/hermes/config/templates
        environment:
            CONTACT_FORM_CONFIGS_FOLDER: /hermes/config/forms
            MAIL_CONFIGS_FOLDER: /hermes/config/mails
            TEMPLATES_FOLDER: /hermes/config/templates

    homunculus:
        image: testadirapa/homunculus:latest
        restart: always
        depends_on:
            mongodb-init:
                condition: service_completed_successfully
                restart: true
        networks:
            - mongo-network
        ports:
            -   8086:8080
        environment:
            AUTH_SECRET: ${AUTH_SECRET}
            REFRESH_SECRET: ${REFRESH_SECRET}
            MONGODB_USERNAME: ${MONGODB_ADMIN_USR}
            MONGODB_PASSWORD: ${MONGODB_ADMIN_PWD}
            MONGODB_IP: mongodb
            MONGODB_PORT: 27017
            MONGODB_DATABASE: ${HOMUNCULUS_DB}
            HOMUNCULUS_URL: ${HOMUNCULUS_URL}
            HERMES_URL: http://hermes:8081
            RESET_PASSWORD_TEMPLATE_ID: ${RESET_PASSWORD_TEMPLATE_ID}
            INVITE_TEMPLATE_ID: ${INVITE_TEMPLATE_ID}

    homunculus-desk:
        build: ./homunculus-desk
        restart: always
        networks:
            - mongo-network
        ports:
            - 8083:80
        healthcheck:
            test: curl http://localhost
            interval: 60s
            retries: 5
            start_period: 20s
            timeout: 10s

networks:
    mongo-network:
        driver: bridge